# Generated by Django 3.0.1 on 2022-10-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200201_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
